import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, BookOpen, Lightbulb, RotateCcw, Users, Search, Wrench } from 'lucide-react';
import { FOOTBRIDGE_STORAGE_KEY, buildQuestionSet, defaultFootbridgeScenario, diagnosisOptions, discoveryFacts, initialFootbridgeState, materialProfiles, projectConsequences, projectMath, questionIndexById, type FootbridgeMaterial, type FootbridgeState } from '../data/footbridgeMission';
type UnityCommand={type:'FOOTBRIDGE_STATE'|'FOOTBRIDGE_TEST';payload:unknown}; type Screen='welcome'|'explore'|'notebook'|'challenge'|'construction'|'test'|'diagnose';
const art:Record<number,string>={1:'/footbridge/mission-1-meet-the-communities.png',2:'/footbridge/mission-2-explore-the-river.png',3:'/footbridge/mission-3-choose-your-bridge.png',4:'/footbridge/mission-4-get-the-materials.png',5:'/footbridge/mission-5-plan-money-deliveries.png',6:'/footbridge/mission-6-build-and-check.png',7:'/footbridge/mission-7-test-fix-celebrate.png'};
const meta=[['Meet the Communities','🏘️'],['Explore the River','🌊'],['Choose Your Bridge','🧩'],['Get the Materials','📦'],['Plan Money & Deliveries','🚚'],['Build & Check','🛠️'],['Test, Fix & Celebrate','🎉']];
function unity(command:UnityCommand){window.dispatchEvent(new CustomEvent('mezzo:unity-command',{detail:command}));(window as Window&{unityInstance?:{SendMessage?:(a:string,b:string,c:string)=>void}}).unityInstance?.SendMessage?.('MezzoBridgeController','ReceiveWebCommand',JSON.stringify(command))}
function saved():FootbridgeState{try{return{...initialFootbridgeState,...JSON.parse(localStorage.getItem(FOOTBRIDGE_STORAGE_KEY)||'{}')}}catch{return initialFootbridgeState}}
function mission(i:number){if(i<=3)return 2;if(i===4)return 3;if(i<=12)return 4;if(i<=16)return 5;if(i===17)return 6;return 7}
function Scene({n}:{n:number}){const[bad,setBad]=useState(false);useEffect(()=>setBad(false),[n]);return bad?<div className="flex min-h-[280px] items-center justify-center bg-cyan-900/30 text-7xl">{meta[n-1][1]}</div>:<img src={art[n]} onError={()=>setBad(true)} className="h-full min-h-[280px] w-full object-cover" alt={meta[n-1][0]}/>}
export default function FootbridgeMissionEngine(){const[state,setState]=useState(saved);const[screen,setScreen]=useState<Screen>(()=>saved().notebook.length?'challenge':'welcome');const[input,setInput]=useState('');const[feedback,setFeedback]=useState('');const[found,setFound]=useState(()=>saved().notebook.map(x=>x.key));const[result,setResult]=useState<'idle'|'pass'|'fail'>('idle');const[hint,setHint]=useState(false);const[repairing,setRepairing]=useState<string|null>(null);const qs=useMemo(()=>buildQuestionSet(state.material),[state.material]);const q=qs[Math.min(state.currentQuestion,qs.length-1)];const all=discoveryFacts.every(x=>found.includes(x.key));const mn=state.currentQuestion>=qs.length?7:mission(state.currentQuestion);const cons=projectConsequences(state);const math=state.material?projectMath(state.material):null;const diagnoses=diagnosisOptions(state);const progress=Math.min(100,Math.round(Object.keys(state.answers).length/qs.length*100));
useEffect(()=>{localStorage.setItem(FOOTBRIDGE_STORAGE_KEY,JSON.stringify(state));unity({type:'FOOTBRIDGE_STATE',payload:{...state,consequences:projectConsequences(state)}})},[state]);
function discover(key:string){const f=discoveryFacts.find(x=>x.key===key);if(!f||found.includes(key))return;setFound(v=>[...v,key]);setState(s=>({...s,notebook:[...s.notebook,f]}))}
function submit(answer:string){if(!q)return;const choosing=q.id==='q5-material',mat=choosing?answer as FootbridgeMaterial:state.material,r=q.evaluate(answer,mat,defaultFootbridgeScenario),old=state.answers[q.id];setState(s=>({...s,material:choosing?mat:s.material,answers:{...s.answers,[q.id]:answer},warnings:r.correct?s.warnings:[...s.warnings,`${q.title}: ${r.note}`],currentQuestion:repairing?s.currentQuestion:Math.min(s.currentQuestion+1,buildQuestionSet(mat).length),redesignCount:repairing?(s.redesignCount||0)+1:s.redesignCount,redesignHistory:repairing?[...(s.redesignHistory||[]),{cause:repairing,questionId:q.id,oldAnswer:old,newAnswer:answer}]:s.redesignHistory}));setFeedback(repairing?`🔧 Redesign saved. ${r.note}`:r.correct?`🌟 Nice work! ${r.note}`:`🧠 Decision recorded. ${r.note} The project will show the consequence later.`);setInput('');setHint(false);if(repairing){setRepairing(null);setScreen('construction');setResult('idle')}}
function test(){const c=projectConsequences(state),pass=c.constructionComplete&&!c.connectionShortage&&!c.floodRisk;setResult(pass?'pass':'fail');setState(s=>({...s,phase:pass?'complete':'test'}));unity({type:'FOOTBRIDGE_TEST',payload:{pass,consequences:c}})}
function diagnose(questionId:string,label:string){if(!state.material)return;const idx=questionIndexById(state.material,questionId);if(idx<0)return;setState(s=>({...s,currentQuestion:idx,diagnosisAttempts:(s.diagnosisAttempts||0)+1}));setRepairing(label);setFeedback('');setInput('');setScreen('challenge')}
function reset(){localStorage.removeItem(FOOTBRIDGE_STORAGE_KEY);setState(initialFootbridgeState);setFound([]);setScreen('welcome');setResult('idle');setRepairing(null)}
const btn='rounded-xl bg-emerald-500 px-5 py-3 font-black text-slate-950 hover:bg-emerald-400 disabled:opacity-40';
return <main className="min-h-screen bg-slate-950 p-4 text-white"><div className="mx-auto max-w-6xl space-y-4"><header className="flex items-center justify-between rounded-3xl bg-white/5 px-5 py-4"><div><p className="text-xs font-black uppercase tracking-widest text-emerald-300">Mezzo Maths Adventure</p><b>Connecting Communities</b></div><button onClick={reset} className="rounded-xl bg-white/10 p-2"><RotateCcw size={18}/></button></header><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full bg-emerald-400" style={{width:`${progress}%`}}/></div>
{screen==='welcome'&&<section className="grid overflow-hidden rounded-[2rem] bg-slate-900 lg:grid-cols-2"><Scene n={1}/><div className="p-8"><p className="font-black text-yellow-300">YOUR ADVENTURE BEGINS</p><h1 className="mt-3 text-4xl font-black">Can you connect Adom & Nkabom?</h1><p className="mt-5 text-lg text-slate-200">Investigate, calculate, procure, build, inspect and test your solution.</p><button onClick={()=>setScreen('explore')} className={`${btn} mt-7 flex gap-2`}>Start exploring <ArrowRight/></button></div></section>}
{screen==='explore'&&<section className="grid overflow-hidden rounded-[2rem] bg-slate-900 lg:grid-cols-2"><Scene n={1}/><div className="p-7"><h2 className="flex gap-3 text-3xl font-black"><Users/> Meet the Communities</h2><p className="mt-3 text-slate-300">Explore every clue. The facts stay in your Project Notebook.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{discoveryFacts.map(f=><button key={f.key} disabled={found.includes(f.key)} onClick={()=>discover(f.key)} className="rounded-2xl border border-white/10 bg-white/5 p-4 text-left disabled:bg-emerald-400/10"><b>{found.includes(f.key)?'✓ ':'🔎 '}{f.label}</b>{found.includes(f.key)&&<p className="mt-2 text-emerald-200">{f.value}</p>}</button>)}</div>{all&&<button onClick={()=>setScreen('notebook')} className={`${btn} mt-6`}>Open notebook</button>}</div></section>}
{screen==='notebook'&&<section className="rounded-[2rem] bg-slate-900 p-8"><h2 className="flex gap-3 text-3xl font-black"><BookOpen/> Project Notebook</h2><div className="mt-5 grid gap-3 sm:grid-cols-3">{state.notebook.map(e=><div key={e.key} className="rounded-2xl bg-white/5 p-4"><small>{e.label}</small><p className="text-xl font-black text-emerald-200">{e.value}</p></div>)}</div><button onClick={()=>setScreen('challenge')} className={`${btn} mt-6`}>Continue mission</button></section>}
{screen==='challenge'&&all&&state.currentQuestion<qs.length&&<section className="grid overflow-hidden rounded-[2rem] bg-slate-900 lg:grid-cols-[.8fr_1.2fr]"><Scene n={repairing?7:mn}/><div className="p-7">{repairing&&<div className="mb-4 rounded-2xl bg-amber-400/10 p-4 text-amber-100"><b>🔧 REDESIGN MODE</b><p className="mt-1">Observed symptom: {repairing}</p><small>Your original answer remains in redesign history.</small></div>}<p className="font-black text-emerald-300">{meta[repairing?6:mn-1][1]} Mission {repairing?7:mn}</p><h2 className="text-3xl font-black">{q.title}</h2><p className="mt-4 text-lg">{q.prompt}</p>{math&&<p className="mt-3 rounded-xl bg-cyan-400/10 p-3 text-sm">Selected: <b>{materialProfiles[state.material!].title}</b> · Project length: <b>{math.length} m</b></p>}{q.hint&&<div className="mt-4"><button onClick={()=>setHint(v=>!v)} className="flex gap-2 text-amber-200"><Lightbulb size={18}/> Need a clue?</button>{hint&&<p className="mt-2 rounded-xl bg-amber-300/10 p-3">{q.hint}</p>}</div>}{q.type==='choice'?<div className="mt-5 grid gap-3">{q.options?.map(o=><button key={o} onClick={()=>submit(o)} className="rounded-2xl bg-white/10 p-4 text-left font-black">{o}</button>)}</div>:<div className="mt-5 flex gap-3"><input value={input} onChange={e=>setInput(e.target.value)} className="min-w-0 flex-1 rounded-2xl bg-white p-4 text-xl font-black text-slate-950" placeholder="Type your answer"/><span className="self-center">{q.unit}</span><button onClick={()=>submit(input)} disabled={!input.trim()} className={btn}>Use answer</button></div>}{feedback&&<div className="mt-4 rounded-2xl bg-indigo-400/10 p-4">{feedback}</div>}</div></section>}
{screen==='challenge'&&state.currentQuestion>=qs.length&&<section className="grid overflow-hidden rounded-[2rem] bg-slate-900 lg:grid-cols-2"><Scene n={6}/><div className="p-7"><h2 className="text-3xl font-black">Construction & Inspection</h2><p className="mt-3 text-slate-300">Your earlier mathematics is now visible at the project site.</p><div className="mt-5 space-y-2">{cons.issues.length?cons.issues.map(x=><p key={x} className="rounded-xl bg-amber-400/10 p-3">⚠️ {x}</p>):<p className="rounded-xl bg-emerald-400/10 p-3">✓ No visible construction shortages detected.</p>}</div><button onClick={()=>setScreen('test')} className={`${btn} mt-6`}>Authorise testing</button></div></section>}
{screen==='construction'&&<section className="grid overflow-hidden rounded-[2rem] bg-slate-900 lg:grid-cols-2"><Scene n={6}/><div className="p-7"><h2 className="text-3xl font-black">Reconstruction complete</h2><p className="mt-3">Your revised calculation has updated the project state.</p><div className="mt-5 space-y-2">{cons.issues.length?cons.issues.map(x=><p key={x} className="rounded-xl bg-amber-400/10 p-3">⚠️ {x}</p>):<p className="rounded-xl bg-emerald-400/10 p-3">✓ The corrected project is ready for inspection.</p>}</div><button onClick={()=>setScreen('test')} className={`${btn} mt-6`}>Retest project</button></div></section>}
{screen==='test'&&<section className="grid overflow-hidden rounded-[2rem] bg-slate-900 lg:grid-cols-2"><Scene n={7}/><div className="p-7"><h2 className="text-3xl font-black">Three-Stage Project Test</h2><p className="mt-3 text-slate-300">Normal use → peak use → environmental test.</p>{result==='idle'&&<button onClick={test} className={`${btn} mt-6`}>Run tests</button>}{result==='pass'&&<div className="mt-6 rounded-2xl bg-emerald-400/10 p-5"><h3 className="text-2xl font-black text-emerald-200">{(state.redesignCount||0)>0?'PROJECT APPROVED AFTER REDESIGN':'PROJECT APPROVED'}</h3><p className="mt-2">Adom and Nkabom are now connected. Redesign cycles: {state.redesignCount||0}.</p></div>}{result==='fail'&&<div className="mt-6"><div className="rounded-2xl bg-amber-400/10 p-5"><h3 className="text-2xl font-black text-amber-200">TESTING STOPPED</h3><p className="mt-2">Inspect the symptoms before changing your calculations.</p>{cons.issues.map(x=><p key={x} className="mt-2">• {x}</p>)}</div><button onClick={()=>setScreen('diagnose')} className={`${btn} mt-5 flex gap-2`}><Search/> Investigate the cause</button></div>}</div></section>}
{screen==='diagnose'&&<section className="grid overflow-hidden rounded-[2rem] bg-slate-900 lg:grid-cols-2"><Scene n={7}/><div className="p-7"><h2 className="text-3xl font-black">Diagnose the problem</h2><p className="mt-3 text-slate-300">Use your notebook, calculations, delivery log and observations. Which earlier decision should you investigate?</p><div className="mt-5 grid gap-3">{diagnoses.map(d=><button key={d.id} onClick={()=>diagnose(d.questionId,d.label)} className="rounded-2xl border border-white/10 bg-white/5 p-4 text-left hover:bg-white/10"><b className="flex gap-2"><Wrench size={18}/>{d.label}</b><small className="mt-2 block text-slate-400">Open only the related calculation</small></button>)}</div><p className="mt-5 text-sm text-slate-400">Diagnosis attempts: {state.diagnosisAttempts||0} · Redesigns: {state.redesignCount||0}</p></div></section>}
<div className="rounded-2xl border border-amber-300/20 bg-amber-300/5 p-3 text-center text-xs text-amber-100">Educational simulation only. Structural values are fictional learning data and must not be used for real bridge construction.</div></div></main>}
